version: '3.3'

services:
  database:
    image: postgres:14-alpine3.15
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - $PWD/postgres:/var/lib/postgresql
